# Site settings
name: Name
title: Title
description: Description
url: http://google.com
baseurl: ""
email:
social:
  - title: email
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: codepen
    url:
  - title: github
    url:
  - title: linkedin
    url:

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
